'use strict';

export const FETCH_INDEX_DATA_SUCCESS = 'FETCH_INDEX_DATA_SUCCESS';
export const FETCH_INDEX_DATA_FAILURE = 'FETCH_INDEX_DATA_FAILURE';
export const FETCH_INDEX_DATE_REQUEST = 'FETCH_INDEX_DATE_REQUEST';